// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALnN2QJODqY-SFX0Dyde7f9T61Xy7BQPs',
    appId: '1:607528818092:web:5f5b55ecdc4a2528a6d609',
    messagingSenderId: '607528818092',
    projectId: 'gomokuonline-1c33d',
    authDomain: 'gomokuonline-1c33d.firebaseapp.com',
    databaseURL: 'https://gomokuonline-1c33d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gomokuonline-1c33d.appspot.com',
    measurementId: 'G-M0CEEXG81C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH6XVTJFxKKy6zG4vIl4ibNFHGIC4Vj4M',
    appId: '1:607528818092:android:ade3cb6436494567a6d609',
    messagingSenderId: '607528818092',
    projectId: 'gomokuonline-1c33d',
    databaseURL: 'https://gomokuonline-1c33d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gomokuonline-1c33d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZYjthdHTUbo08NuYKIXSaqKZPrG_tIXc',
    appId: '1:607528818092:ios:e8e9247b166a802da6d609',
    messagingSenderId: '607528818092',
    projectId: 'gomokuonline-1c33d',
    databaseURL: 'https://gomokuonline-1c33d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gomokuonline-1c33d.appspot.com',
    iosClientId: '607528818092-hka9spgmtn9om923esqk1iu9vn8sr8ti.apps.googleusercontent.com',
    iosBundleId: 'com.example.gomokuOnlineApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZYjthdHTUbo08NuYKIXSaqKZPrG_tIXc',
    appId: '1:607528818092:ios:e8e9247b166a802da6d609',
    messagingSenderId: '607528818092',
    projectId: 'gomokuonline-1c33d',
    databaseURL: 'https://gomokuonline-1c33d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gomokuonline-1c33d.appspot.com',
    iosClientId: '607528818092-hka9spgmtn9om923esqk1iu9vn8sr8ti.apps.googleusercontent.com',
    iosBundleId: 'com.example.gomokuOnlineApp',
  );
}
